// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miucczhudcskyzyrnzhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pdWNjemh1ZGNza3l6eXJuemhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDA3ODQsImV4cCI6MjA2ODk3Njc4NH0.uWhebmI9Uso6p2KnH6EKG5a7R1c4x8tJPUowI3Xe-Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});